// Generated by tools/generate_potion_assets.py.
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t potion_material_images[12];
extern const lv_image_dsc_t potion_bottle_images[6];
extern const lv_image_dsc_t potion_brewing_images[3];
extern const lv_image_dsc_t potion_muddy_images[3];
extern const lv_image_dsc_t potion_property_images[8];
extern const lv_image_dsc_t potion_navigation_images[6];
extern const lv_image_dsc_t potion_radar_status_images[3];
