#include "potion_hash.h"
#include "potion_model.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void test_sha256(void){uint8_t d[32];potion_sha256("abc",3,d);static const uint8_t e[32]={0xba,0x78,0x16,0xbf,0x8f,0x01,0xcf,0xea,0x41,0x41,0x40,0xde,0x5d,0xae,0x22,0x23,0xb0,0x03,0x61,0xa3,0x96,0x17,0x7a,0x9c,0xb4,0x10,0xff,0x61,0xf2,0x00,0x15,0xad};assert(memcmp(d,e,32)==0);}
static void test_generation_stable(void){uint16_t a=potion_material_for_signal(POTION_SOURCE_WIFI,0x123456789abcdef0ULL);assert(a==potion_material_for_signal(POTION_SOURCE_WIFI,0x123456789abcdef0ULL));assert(a<POTION_MATERIAL_COUNT);}
static void test_collect_cooldown(void){potion_player_t p;potion_player_defaults(&p);int64_t r=0;potion_clock_t clock={.epoch=1000,.uptime_sec=10,.session_id=7,.epoch_valid=true};assert(!potion_cooldown_any_active(&p,&clock));assert(potion_collect(&p,POTION_SOURCE_WIFI,1,0,&clock,&r));assert(potion_cooldown_any_active(&p,&clock));clock.epoch=1001;assert(!potion_collect(&p,POTION_SOURCE_WIFI,1,0,&clock,&r)&&r==899);clock.epoch=1900;assert(!potion_cooldown_any_active(&p,&clock));assert(potion_collect(&p,POTION_SOURCE_WIFI,1,0,&clock,&r));clock=(potion_clock_t){.uptime_sec=100,.session_id=7,.epoch_valid=false};assert(potion_collect(&p,POTION_SOURCE_BLE_TEMP,2,1,&clock,&r));clock.uptime_sec=101;assert(!potion_collect(&p,POTION_SOURCE_BLE_TEMP,2,1,&clock,&r)&&r==899);clock=(potion_clock_t){.uptime_sec=1,.session_id=8,.epoch_valid=false};assert(potion_cooldown_remaining(&p,2,&clock)==900);assert(potion_cooldown_checkpoint(&p,&clock));clock.uptime_sec=61;assert(potion_cooldown_remaining(&p,2,&clock)==840);}
static void test_radar_aggregation(void){potion_player_t p;potion_player_defaults(&p);potion_clock_t clock={.session_id=9};potion_material_signal_t s[]={{1,-60,2,POTION_SOURCE_WIFI},{2,-50,2,POTION_SOURCE_BLE_STABLE},{3,-55,4,POTION_SOURCE_WIFI},{4,-40,8,POTION_SOURCE_WIFI}};potion_radar_item_t out[3];assert(potion_radar_aggregate(&p,s,4,&clock,out,3,false)==3);assert(out[0].material_id==2&&out[0].fingerprint==2);int64_t remaining=0;assert(potion_collect(&p,POTION_SOURCE_WIFI,4,8,&clock,&remaining));assert(potion_radar_aggregate(&p,s,4,&clock,out,3,true)==2);for(size_t i=0;i<2;++i)assert(out[i].fingerprint!=4);}
static void test_radar_top_ten(void){potion_player_t p;potion_player_defaults(&p);potion_clock_t clock={.session_id=9};potion_material_signal_t signals[20];for(size_t i=0;i<20;++i)signals[i]=(potion_material_signal_t){i+1,(int8_t)(-59+(int)i),(uint16_t)(i%POTION_MATERIAL_COUNT),POTION_SOURCE_WIFI};potion_radar_item_t out[10];assert(potion_radar_select(&p,signals,20,&clock,out,10)==10);bool found_strongest=false;for(size_t i=0;i<10;++i){assert(out[i].rssi>=-49);found_strongest|=out[i].rssi==-40;if(i)assert(potion_signal_strength_percent(out[i-1].source,out[i-1].rssi)>=potion_signal_strength_percent(out[i].source,out[i].rssi));}assert(found_strongest);}
static void test_explore_progress(void){potion_explore_progress_t p;potion_explore_reset(&p);assert(potion_explore_update(&p,7,30,-85,0)<100);potion_explore_update(&p,7,70,-64,5000);assert(!potion_explore_collectable(&p));potion_explore_update(&p,7,68,-61,10000);potion_explore_update(&p,7,75,-58,11000);assert(potion_explore_collectable(&p));assert(potion_explore_update(&p,7,72,-60,12000)==100);assert(potion_explore_update(&p,7,50,-76,13000)<=90);assert(!potion_explore_collectable(&p));assert(potion_explore_update(&p,7,70,-62,14000)==100);assert(potion_explore_collectable(&p));potion_explore_update(&p,8,80,-55,15000);assert(!potion_explore_collectable(&p)&&p.fingerprint==8);}
static void test_high_strength_collects_within_thirty_seconds(void){potion_explore_progress_t moving,still;potion_explore_reset(&moving);potion_explore_reset(&still);potion_explore_update(&moving,9,100,-55,0);potion_explore_update(&moving,9,100,-61,10000);assert(!potion_explore_collectable(&moving));assert(potion_explore_update(&moving,9,100,-54,20000)==100);assert(potion_explore_collectable(&moving));potion_explore_update(&still,10,100,-55,0);potion_explore_update(&still,10,100,-55,10000);potion_explore_update(&still,10,100,-55,20000);potion_explore_update(&still,10,100,-55,30000);assert(!potion_explore_collectable(&still));}
static void test_dynamic_signal_threshold(void){potion_explore_progress_t p;potion_explore_reset(&p);potion_explore_update(&p,12,52,-74,0);potion_explore_update(&p,12,55,-68,5000);potion_explore_update(&p,12,55,-72,10000);assert(!potion_explore_collectable(&p));uint8_t threshold=potion_signal_threshold_relax(66,55);assert(threshold==55);potion_explore_update(&p,12,56,-67,12000);assert(potion_explore_collectable_at(&p,threshold));assert(potion_explore_score_at(&p,threshold)==100);threshold=potion_signal_threshold_recover(threshold,56);assert(threshold>55&&threshold<=66);assert(potion_signal_threshold_relax(threshold,90)==threshold);assert(potion_signal_threshold_recover(66,100)==66);}
static void test_radar_display_helpers(void){potion_duration_unit_t unit;assert(potion_duration_ceil(59,&unit)==59&&unit==POTION_DURATION_SECONDS);assert(potion_duration_ceil(60,&unit)==1&&unit==POTION_DURATION_MINUTES);assert(potion_duration_ceil(61,&unit)==2&&unit==POTION_DURATION_MINUTES);assert(potion_duration_ceil(3600,&unit)==1&&unit==POTION_DURATION_HOURS);assert(potion_duration_ceil(86399,&unit)==24&&unit==POTION_DURATION_HOURS);assert(potion_duration_ceil(86400,&unit)==1&&unit==POTION_DURATION_DAYS);assert(potion_signal_strength_percent(POTION_SOURCE_WIFI,-95)==0);assert(potion_signal_strength_percent(POTION_SOURCE_WIFI,-45)==100);assert(potion_signal_strength_percent(POTION_SOURCE_WIFI,-78)>potion_signal_strength_percent(POTION_SOURCE_WIFI,-90));int wifi=potion_signal_strength_percent(POTION_SOURCE_WIFI,-60),ble=potion_signal_strength_percent(POTION_SOURCE_BLE_STABLE,-70);assert(abs(wifi-ble)<=5);potion_radar_item_t items[10];for(size_t i=0;i<10;++i)items[i]=(potion_radar_item_t){i+1,(int8_t)(-40-(int)i),(uint16_t)(i%POTION_MATERIAL_COUNT),POTION_SOURCE_WIFI,0,false};potion_radar_point_t points[10];potion_radar_layout(items,10,points);int inner=points[0].x*points[0].x+points[0].y*points[0].y;int outer=points[9].x*points[9].x+points[9].y*points[9].y;assert(inner>=144&&inner<=256);assert(outer>2025);for(size_t i=0;i<10;++i)assert(points[i].x>=-54&&points[i].x<=54&&points[i].y>=-54&&points[i].y<=54);}
static void test_attribute_priority_and_muddy(void){uint16_t glow[4]={6,6,6,6};assert(potion_match(glow)==0);uint16_t dragon[4]={11,11,3,3};assert(potion_match(dragon)==5);uint16_t muddy[4]={3,3,3,3};assert(potion_match(muddy)==POTION_MUDDY_ID);}
static void test_brew_atomic_history(void){potion_player_t p,c;potion_player_defaults(&p);p.lab_set=1;p.lab_fingerprint=9;uint16_t recipe[4]={3,3,3,3};p.materials[3]=4;uint16_t id=0;uint32_t seed=0;assert(potion_brew_candidate(&p,recipe,&c,&id,&seed));assert(id==POTION_MUDDY_ID&&seed&&c.potions[id]==1&&c.materials[3]==0);assert(p.materials[3]==4&&p.potions[id]==0);assert(potion_recipe_history_count(&c,id)==1);assert(potion_recipe_history_at(&c,id,0)->material_id[0]==3);p=c;p.materials[3]=4;assert(potion_brew_candidate(&p,recipe,&c,&id,&seed));assert(potion_recipe_history_count(&c,id)==1);}
static void test_history_eviction(void){potion_player_t p,c;potion_player_defaults(&p);p.lab_set=1;p.lab_fingerprint=1;for(unsigned i=0;i<12;++i)p.materials[i]=100;uint16_t first[4]={0},last[4]={0};unsigned made=0;for(uint16_t a=0;a<12&&made<11;++a)for(uint16_t b=a;b<12&&made<11;++b)for(uint16_t d=b;d<12&&made<11;++d)for(uint16_t e=d;e<12&&made<11;++e){uint16_t r[4]={a,b,d,e};if(potion_match(r)!=POTION_MUDDY_ID)continue;if(!made)memcpy(first,r,sizeof(first));memcpy(last,r,sizeof(last));uint16_t id;assert(potion_brew_candidate(&p,r,&c,&id,NULL)&&id==POTION_MUDDY_ID);p=c;made++;}assert(made==11);assert(potion_recipe_history_count(&p,POTION_MUDDY_ID)==10);assert(memcmp(potion_recipe_history_at(&p,POTION_MUDDY_ID,0)->material_id,last,sizeof(last))==0);for(size_t i=0;i<10;++i)assert(memcmp(potion_recipe_history_at(&p,POTION_MUDDY_ID,i)->material_id,first,sizeof(first))!=0);}
static void test_cooldown_capacity(void){potion_player_t p;potion_player_defaults(&p);potion_clock_t clock={.session_id=77};int64_t r=0;for(uint64_t i=1;i<=POTION_COOLDOWN_CAPACITY;i++)assert(potion_collect(&p,POTION_SOURCE_BLE_TEMP,i,0,&clock,&r));assert(!potion_collect(&p,POTION_SOURCE_BLE_TEMP,999,0,&clock,&r));}
static void test_expired_cooldown_eviction(void){potion_player_t p;potion_player_defaults(&p);assert(p.screen_timeout_index==1);potion_clock_t clock={.epoch=1000,.session_id=78,.epoch_valid=true};int64_t r=0;uint64_t shortest_fp=0;uint32_t shortest=UINT32_MAX;for(uint64_t fp=1;fp<=POTION_COOLDOWN_CAPACITY;++fp){uint16_t id=potion_material_for_signal(POTION_SOURCE_WIFI,fp);assert(potion_collect(&p,POTION_SOURCE_WIFI,fp,id,&clock,&r));uint32_t duration=potion_material_def(id)->cooldown_sec;if(duration<shortest){shortest=duration;shortest_fp=fp;}}clock.epoch=1000+172800;uint64_t replacement=9999;uint16_t replacement_id=potion_material_for_signal(POTION_SOURCE_WIFI,replacement);assert(potion_collect(&p,POTION_SOURCE_WIFI,replacement,replacement_id,&clock,&r));bool found_shortest=false,found_replacement=false;for(size_t i=0;i<POTION_COOLDOWN_CAPACITY;++i){found_shortest|=p.cooldowns[i].used&&p.cooldowns[i].fingerprint==shortest_fp;found_replacement|=p.cooldowns[i].used&&p.cooldowns[i].fingerprint==replacement;}assert(!found_shortest&&found_replacement);}
static void test_idle_screen(void){potion_idle_t idle;potion_idle_init(&idle,1000);assert(!potion_idle_poll(&idle,60999,60000));assert(potion_idle_poll(&idle,61000,60000));assert(idle.screen_off);assert(!potion_idle_poll(&idle,121000,60000));assert(potion_idle_note_input(&idle,121000));assert(!idle.screen_off);assert(!potion_idle_note_input(&idle,122000));potion_idle_init(&idle,UINT32_MAX-10);assert(potion_idle_poll(&idle,50,60));}
int main(void){test_sha256();test_generation_stable();test_collect_cooldown();test_radar_aggregation();test_radar_top_ten();test_explore_progress();test_high_strength_collects_within_thirty_seconds();test_dynamic_signal_threshold();test_radar_display_helpers();test_attribute_priority_and_muddy();test_brew_atomic_history();test_history_eviction();test_cooldown_capacity();test_expired_cooldown_eviction();test_idle_screen();puts("potion_model: all tests passed");return 0;}
