#!/usr/bin/env python3
"""Build reproducible LVGL RGB565A8 sprites from approved generated atlases."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "potion_art" / "source"
OUT = ROOT / "assets" / "potion_art" / "sprites"
HEADER = ROOT / "main" / "potion_assets.h"
CODE = ROOT / "main" / "potion_assets.c"
PREVIEW = ROOT / "assets" / "potion_art" / "sprite-preview.png"

SETS = (
    ("material", SOURCE / "materials-atlas-v1.png", 4, 3, 32, 32, "potion_material_images"),
    ("potion", SOURCE / "potions-atlas-v1.png", 3, 2, 40, 40, "potion_bottle_images"),
    ("brewing", SOURCE / "brewing-atlas-v1.png", 3, 1, 96, 80, "potion_brewing_images"),
    ("muddy", SOURCE / "muddy-potion-atlas-v1.png", 3, 1, 48, 48, "potion_muddy_images"),
    ("property", SOURCE / "property-icons-atlas-v1.png", 4, 2, 24, 24, "potion_property_images"),
    ("navigation", SOURCE / "navigation-icons-atlas-v1.png", 3, 2, 40, 40, "potion_navigation_images"),
    ("radar", SOURCE / "radar-status-atlas-v1.png", 3, 1, 20, 20, "potion_radar_status_images"),
)


def sprite(cell: Image.Image, width: int, height: int) -> Image.Image:
    cell = cell.convert("RGBA")
    alpha = cell.getchannel("A")
    box = alpha.point(lambda a: 255 if a >= 32 else 0).getbbox()
    if not box:
        raise ValueError("empty atlas cell")
    crop = cell.crop(box)
    crop.thumbnail((width - 4, height - 4), Image.Resampling.NEAREST)
    canvas = Image.new("RGBA", (width, height))
    canvas.alpha_composite(crop, ((width - crop.width) // 2, (height - crop.height) // 2))
    r, g, b, a = canvas.split()
    a = a.point(lambda v: 0 if v < 32 else (255 if v > 223 else v))
    return Image.merge("RGBA", (r, g, b, a))


def lvgl_bytes(im: Image.Image) -> bytes:
    colors = bytearray()
    alpha = bytearray()
    for r, g, b, a in im.getdata():
        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        colors += value.to_bytes(2, "little")
        alpha.append(a)
    return bytes(colors + alpha)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    records = []
    arrays = []
    preview_rows = []
    for prefix, path, cols, rows, width, height, array in SETS:
        atlas = Image.open(path)
        cell_w, cell_h = atlas.width // cols, atlas.height // rows
        sprites = []
        for index in range(cols * rows):
            x, y = (index % cols) * cell_w, (index // cols) * cell_h
            im = sprite(atlas.crop((x, y, x + cell_w, y + cell_h)), width, height)
            im.save(OUT / f"{prefix}-{index:02d}.png", optimize=True)
            records.append((prefix, index, width, height, lvgl_bytes(im)))
            sprites.append(im)
        arrays.append((prefix, cols * rows, width, height, array))
        preview_rows.append((prefix, sprites))

    declarations = ["// Generated by tools/generate_potion_assets.py.", "#pragma once", '#include "lvgl.h"', ""]
    for _, count, _, _, array in arrays:
        declarations.append(f"extern const lv_image_dsc_t {array}[{count}];")
    HEADER.write_text("\n".join(declarations) + "\n", encoding="utf-8")

    lines = ['// Generated by tools/generate_potion_assets.py.', '#include "potion_assets.h"', '']
    for prefix, index, width, height, data in records:
        name = f"{prefix}_{index:02d}_data"
        lines.append(f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {name}[{len(data)}] = {{")
        for offset in range(0, len(data), 20):
            lines.append("    " + ",".join(f"0x{x:02x}" for x in data[offset:offset + 20]) + ",")
        lines.append("};\n")
    for prefix, count, width, height, array in arrays:
        lines.append(f"const lv_image_dsc_t {array}[{count}] = {{")
        for index in range(count):
            data_len = width * height * 3
            lines.append("    { .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565A8, "
                         f".w = {width}, .h = {height}, .stride = {width * 2} }}, .data_size = {data_len}, .data = {prefix}_{index:02d}_data }},")
        lines.append("};\n")
    CODE.write_text("\n".join(lines), encoding="utf-8")

    row_height = 108
    preview = Image.new("RGBA", (600, row_height * len(preview_rows)), (16, 13, 25, 255))
    draw = ImageDraw.Draw(preview)
    for row, (name, sprites) in enumerate(preview_rows):
        y = row * row_height
        draw.text((8, y + 8), name, fill=(245, 185, 76, 255))
        x = 112
        for im in sprites:
            preview.alpha_composite(im, (x, y + (row_height - im.height) // 2))
            x += im.width + 8
    preview.save(PREVIEW, optimize=True)


if __name__ == "__main__":
    main()
